export const siteContent = {
    about: {
        brand: "Smart it",
        mainIntro: "è un'impresa specializzata in",
        mainHighlight: "servizi di pulizia professionale, manutenzione e facility management",
        mainLocation: "a Milano, Assago, Buccinasco e in tutta la Lombardia.",
        description: "Ci prendiamo cura del vostro immobile in ogni suo aspetto, preservandone il valore nel tempo attraverso interventi mirati e personalizzati: dalla pulizia quotidiana e straordinaria di uffici, aziende e condomini, al lavaggio di facciate e vetrate, fino alla manutenzione di impianti elettrici e idraulici, spazi verdi e aree comuni.",
    },
    hero: {
        imageAlt: "Milano buildings",
        titleStart: "Soluzioni Complete per il",
        titleHighlight: "Facility Management",
        titleEnd: "a Milano",
        description: "Dalla pulizia alla manutenzione, gestiamo ogni aspetto dei tuoi spazi aziendali con professionalità e affidabilità.",
        primaryCta: "Richiedi un Preventivo",
        secondaryCta: "Scopri i Servizi",
    },
    nav: {
        logoAlt: "Smart it",
        logoLabel: "Smart it",
        homeLabel: "Home",
        serviziLabel: "Servizi",
        chiSiamoLabel: "Chi Siamo",
        contattiLabel: "Contatti",
        ctaHref: "/contatti",
        ctaLabel: "Richiedi Preventivo",
        mobileFooterPrimary: "Smart it - Facility Management",
        mobileFooterSecondary: "Milano",
    },
    footer: {
        logoAlt: "Smart it",
        companyDescription: "Soluzioni professionali per la gestione e manutenzione di spazi aziendali a Milano.",
        quickLinksTitle: "Link Rapidi",
        servicesTitle: "Servizi Principali",
        routineCleaning: "Pulizie Ordinarie",
        deepCleaning: "Pulizie Straordinarie",
        businessCleaning: "Pulizie per Aziende",
        maintenance: "Manutenzioni",
        conciergeServices: "Servizi di Portierato",
        contactTitle: "Contatti",
        city: "Milano, Italia",
        phone: "+39 012 345 6789",
        email: "info@smartit.it",
        copyrightSuffix: "Smart it. Tutti i diritti riservati.",
    },
};
