export const siteContent = {
    home: {
        about: {
            brand: "Smart it",
            mainIntro: "è un'impresa specializzata in",
            mainHighlight: "servizi di pulizia professionale, manutenzione e facility management",
            mainLocation: "a Milano, Assago, Buccinasco e in tutta la Lombardia.",
            description: "Ci prendiamo cura del vostro immobile in ogni suo aspetto, preservandone il valore nel tempo attraverso interventi mirati e personalizzati: dalla pulizia quotidiana e straordinaria di uffici, aziende e condomini, al lavaggio di facciate e vetrate, fino alla manutenzione di impianti elettrici e idraulici, spazi verdi e aree comuni.",
        },
        hero: {
            imageAlt: "Milano buildings",
            titleStart: "Soluzioni Complete per il",
            titleHighlight: "Facility Management",
            titleEnd: "a Milano",
            description: "Dalla pulizia alla manutenzione, gestiamo ogni aspetto dei tuoi spazi aziendali con professionalità e affidabilità.",
            primaryCta: "Richiedi un Preventivo",
            secondaryCta: "Scopri i Servizi",
        },
        contacts: {
            title: "Pronto a Migliorare i Tuoi Spazi?",
            description: "Contattaci oggi per un preventivo gratuito e scopri come possiamo aiutarti",
            primaryCta: "Contattaci Ora",
        },
        mainServicesSection: {
            titleStart: "I Nostri",
            titleHighlight: "Servizi Principali",
            description: "Offriamo una gamma completa di servizi per la gestione e manutenzione dei tuoi spazi",
            ctaLabel: "Scopri di più",
        },
        additionalServicesSection: {
            titleStart: "Altri",
            titleHighlight: "Servizi",
            description: "Un'offerta completa per tutte le esigenze di facility management",
            ctaLabel: "Vedi Tutti i Servizi",
            cardCtaLabel: "Scopri di piu",
        },
        whyUs: {
            title: "Perché Scegliere Smart it",
            subtitle: "Il partner ideale per la gestione dei tuoi spazi a Milano",
            consolidatedExperienceTitle: "Esperienza Consolidata",
            consolidatedExperienceDescription: "Anni di esperienza nel settore della gestione facilities a Milano",
            certifiedQualityTitle: "Qualità Certificata",
            certifiedQualityDescription: "Standard elevati e certificazioni nel rispetto delle normative",
            h24AvailabilityTitle: "Disponibilità H24",
            h24AvailabilityDescription: "Interventi programmati e assistenza disponibile quando ne hai bisogno",
            dedicatedSupportTitle: "Supporto Dedicato",
            dedicatedSupportDescription: "Un team professionale sempre a tua disposizione",
        },
    },
    header: {
        logoAlt: "Smart it",
        logoLabel: "Smart it",
        homeLabel: "Home",
        serviziLabel: "Servizi",
        chiSiamoLabel: "Chi Siamo",
        contattiLabel: "Contatti",
        ctaHref: "/contatti",
        ctaLabel: "Richiedi Preventivo",
        mobileFooterPrimary: "Smart it - Facility Management",
        mobileFooterSecondary: "Milano",
    },
    footer: {
        logoAlt: "Smart it",
        companyDescription: "Soluzioni professionali per la gestione e manutenzione di spazi aziendali a Milano.",
        quickLinksTitle: "Link Rapidi",
        servicesTitle: "Servizi Principali",
        routineCleaning: "Pulizie Ordinarie",
        deepCleaning: "Pulizie Straordinarie",
        businessCleaning: "Pulizie per Aziende",
        maintenance: "Manutenzioni",
        conciergeServices: "Servizi di Portierato",
        contactTitle: "Contatti",
        city: "Milano, Italia",
        phone: "+39 012 345 6789",
        email: "info@smartit.it",
        copyrightSuffix: "Smart it. Tutti i diritti riservati.",
    },
    services: {
        routineCleaning: {
            title: "Pulizie ordinarie",
            shortDescription: "Servizi di pulizia regolare per mantenere i tuoi spazi sempre impeccabili.",
            description: "Il nostro servizio di pulizie ordinarie garantisce ambienti sempre puliti, igienizzati e accoglienti. Offriamo soluzioni personalizzate per uffici, negozi e spazi commerciali con personale qualificato e prodotti professionali.",
        },
        deepCleaning: {
            title: "Pulizie straordinarie",
            shortDescription: "Interventi approfonditi per sanificazione e pulizia straordinaria.",
            description: "Le pulizie straordinarie sono interventi approfonditi e mirati per situazioni particolari: traslochi, eventi, ristrutturazioni o semplicemente quando serve una pulizia piu accurata del normale.",
        },
        businessAndOfficeCleaning: {
            title: "Pulizie per Aziende e Uffici",
            shortDescription: "Soluzioni professionali per spazi di lavoro puliti e accoglienti.",
            description: "Offriamo servizi di pulizia dedicati ad aziende e uffici a Milano. Comprendiamo l'importanza di ambienti di lavoro puliti e professionali per la produttivita e l'immagine aziendale.",
        },
        industrialCleaning: {
            title: "Pulizie Industriali",
            shortDescription: "Servizi specializzati per ambienti industriali e produttivi.",
            description: "Pulizie industriali professionali per stabilimenti, magazzini, capannoni e aree produttive. Utilizziamo attrezzature specifiche e personale specializzato per garantire sicurezza e conformita alle normative.",
        },
        condominiumCleaning: {
            title: "Pulizie Condominiali",
            shortDescription: "Manutenzione e pulizia di aree comuni condominiali.",
            description: "Servizi di pulizia per condomini a Milano: scale, androni, cortili, garage e tutte le aree comuni. Garantiamo standard elevati per il benessere di tutti i condomini.",
        },
        maintenance: {
            title: "Manutenzioni",
            shortDescription: "Servizi completi di manutenzione ordinaria e straordinaria.",
            description: "Offriamo servizi completi di manutenzione per edifici, uffici e strutture. Dal piccolo intervento alla manutenzione programmata, ci occupiamo di tutto con professionalita.",
        },
    },
};
